# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for turbo
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for mhz-admin
  - package-ecosystem: "npm"
    directory: "/apps/admin"
    schedule:
      interval: "weekly"

  # Maintain dependencies for mhz-back
  - package-ecosystem: "npm"
    directory: "/apps/back"
    schedule:
      interval: "weekly"

  # Maintain dependencies for mhz-ui
  - package-ecosystem: "npm"
    directory: "/packages/ui"
    schedule:
      interval: "weekly"

  # Maintain dependencies for mhz-validate
  - package-ecosystem: "npm"
    directory: "/packages/validate"
    schedule:
      interval: "weekly"
