name: CI

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.0"
      - name: Install
        run: npm i
      - name: Create Admin .env
        uses: SpicyPizza/create-envfile@v2.0.2
        with:
          envkey_VITE_API: ${{ secrets.ENV_VITE_API }}
          envkey_VITE_PATH_UPLOAD: ${{ secrets.VITE_PATH_UPLOAD }}
          directory: apps/admin/
      - name: Create Backend .env
        uses: SpicyPizza/create-envfile@v2.0.2
        with:
          envkey_DATABASE: ${{ secrets.DATABASE }}
          envkey_SECRET: ${{ secrets.SECRET }}
          envkey_PORT: ${{ secrets.PORT }}
          directory: apps/back/
      - name: Build
        run: npm run build
      - name: Lint check
        run: npm run lint
      - name: TS check
        run: npm run ts
      - name: Deploy Admin
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: apps/admin/dist/
          target: ${{ secrets.SSH_PATH }}
      - name: Deploy Backend
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "apps/back/build,apps/back/package.json,apps/back/.env"
          target: ${{ secrets.SSH_PATH }}
      - name: Deploy Storybook
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "packages/ui/storybook-static"
          target: ${{ secrets.SSH_PATH }}
      - name: Install Backend deps and Reload PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ secrets.SSH_PATH_BACKEND }}
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm i
            pm2 reload mhz
